Server:
  port: "8081"

DB:
  databaseURL: "sdvcsd"
  port: 5432
  maxOpenConnection: 15
  maxIdleConnection: 10
  connectionLifetime: "600s"

Token:
  authToken: "test-token"

Logger:
  loggerLevel: "info"